$(document).ready(function(){
	$("#show").hide();
	$("#shows").hide();
	$("#delta").show();
	$("#delt").mouseover(function(){
	 	$("#show").show();
	 	$("#shows").show();
	 	$("#delta").hide();
	 });
	$("#delt").mouseout(function(){
        $("#show").hide();
	 	$("#shows").hide();
	 	$("#delta").show();
	 });
	$("#show1").hide();
	$("#shows1").hide();
	$("#delta1").show();
	$("#delt1").mouseover(function(){
	 	$("#show1").show();
	 	$("#shows1").show();
	 	$("#delta1").hide();
	 });
	$("#delt1").mouseout(function(){
        $("#show1").hide();
	 	$("#shows1").hide();
	 	$("#delta1").show();
	 });
	$("#show2").hide();
	$("#shows2").hide();
	$("#delta2").show();
	$("#delt2").mouseover(function(){
	 	$("#show2").show();
	 	$("#shows2").show();
	 	$("#delta2").hide();
	 });
	$("#delt2").mouseout(function(){
        $("#show2").hide();
	 	$("#shows2").hide();
	 	$("#delta2").show();
	 });
	$("#show3").hide();
	$("#shows3").hide();
	$("#delta3").show();
	$("#delt3").mouseover(function(){
	 	$("#show3").show();
	 	$("#shows3").show();
	 	$("#delta3").hide();
	 });
	$("#delt3").mouseout(function(){
        $("#show3").hide();
	 	$("#shows3").hide();
	 	$("#delta3").show();
	 });
});
